replicaCount: 2

image:
  # TODO: set up
  repository: ghcr.io/kthcloud/podsh/podsh
  #tag: "v1.0.0"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer

  annotations: {}

  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP

rbac:
  enabled: true
  # TODO: use the deploy ns on kthcloud
  namespace: deploy
  serviceAccountName: podsh-server-account

networkpolicy:
  # This is disabled because I havent figured out what it needs to talk to fully
  enabled: false

env:
  # TODO: configure viper env mapper
  - name: PODSH_PROFILE
    value: prod
  - name: PODSH_LOG_LEVEL
    value: info
  - name: PODSH_REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: redis-password

config:
  # TODO: config for prod
  enabled: true
  mountPath: /etc/podsh
  data:
    config.yaml: |
      kubeconfig: ""

resources:
  limits:
    cpu: 2000m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

liveness:
  path: /livez
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readiness:
  path: /readyz
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

imagePullSecrets: []

redis:
  enabled: true
  auth:
    password: "changeme"

syncdb:
  enabled: true
  externalMongo:
    ip: 1.1.1.1

mongo:
  enabled: false

ssh:
  #hostSignerKey: |
  #  -----BEGIN OPENSSH PRIVATE KEY-----
  #  ...
  #  -----END OPENSSH PRIVATE KEY-----

