{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
type: Opaque
stringData:
  redis-password: {{ required "Redis password required" .Values.auth.password }}
{{- end }}

