{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Secret name for redis is required" .Values.auth.secretName }}
type: Opaque
stringData:
  password: {{ required "Redis password required" .Values.auth.password }}
{{- end }}

