environments:
  dev:
    values:
      - environments/dev/values.yaml
  prod:
    values:
      - environments/prod/values.yaml

---
repositories:

---
releases:
  
  - name: podsh
    namespace: podsh
    chart: ./chart
    values:
      - environments/{{ .Environment.Name }}/values.yaml

