{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.rbac.namespace }}
  labels:
    app.kubernetes.io/name: podsh-server
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

