apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    app: {{ include "mongo.name" . }}
spec:
  serviceName: {{ include "mongo.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mongo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.name" . }}
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data/db
            {{- if .Values.preload.enabled }}
            - name: preload-scripts
              mountPath: /docker-entrypoint-initdb.d
              readonly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.preload.enabled }}
        - name: preload-scripts
          configMap:
            name: {{ include "mongo.fullname" . }}-preload
            defaultMode: 0644
        {{- end }}
  volumeClaimTemplates:
    {{- if .Values.persistence.enabled }}
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}
    {{- end }}

