// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: identity_events.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	// Sent during initial full snapshot phase.
	EventKind_SNAPSHOT EventKind = 1
	// Sent for live upserts (insert/update).
	EventKind_UPSERT EventKind = 2
	// Sent when user is deleted or disabled.
	EventKind_DELETE EventKind = 3
	// Optional marker that snapshot phase is complete.
	EventKind_SNAPSHOT_COMPLETE EventKind = 4
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "SNAPSHOT",
		2: "UPSERT",
		3: "DELETE",
		4: "SNAPSHOT_COMPLETE",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"SNAPSHOT":               1,
		"UPSERT":                 2,
		"DELETE":                 3,
		"SNAPSHOT_COMPLETE":      4,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_identity_events_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_identity_events_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{0}
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional logical subscriber ID (for logging / auditing)
	SubscriberId string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// If true, forces a full snapshot rebuild.
	FullSnapshot  bool `protobuf:"varint,2,opt,name=full_snapshot,json=fullSnapshot,proto3" json:"full_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_identity_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeRequest) GetFullSnapshot() bool {
	if x != nil {
		return x.FullSnapshot
	}
	return false
}

type IdentityEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic event ID generated by gateway.
	// Not Mongo resume token.
	EventId uint64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Type of event.
	Kind EventKind `protobuf:"varint,2,opt,name=kind,proto3,enum=identitypd.EventKind" json:"kind,omitempty"`
	// Timestamp (server-side) in unix millis.
	TimestampMs int64 `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Payload (only set for UPSERT / SNAPSHOT).
	User          *UserProjection `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityEvent) Reset() {
	*x = IdentityEvent{}
	mi := &file_identity_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityEvent) ProtoMessage() {}

func (x *IdentityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityEvent.ProtoReflect.Descriptor instead.
func (*IdentityEvent) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityEvent) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *IdentityEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *IdentityEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *IdentityEvent) GetUser() *UserProjection {
	if x != nil {
		return x.User
	}
	return nil
}

type UserProjection struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Store full public keys or fingerprints.
	SshPublicKeys []string `protobuf:"bytes,3,rep,name=ssh_public_keys,json=sshPublicKeys,proto3" json:"ssh_public_keys,omitempty"`
	Roles         []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Teams         []string `protobuf:"bytes,5,rep,name=teams,proto3" json:"teams,omitempty"`
	Enabled       bool     `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Optional optimistic version (increment on Mongo updates)
	Version       uint64 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProjection) Reset() {
	*x = UserProjection{}
	mi := &file_identity_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProjection) ProtoMessage() {}

func (x *UserProjection) ProtoReflect() protoreflect.Message {
	mi := &file_identity_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProjection.ProtoReflect.Descriptor instead.
func (*UserProjection) Descriptor() ([]byte, []int) {
	return file_identity_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserProjection) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProjection) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProjection) GetSshPublicKeys() []string {
	if x != nil {
		return x.SshPublicKeys
	}
	return nil
}

func (x *UserProjection) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserProjection) GetTeams() []string {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *UserProjection) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserProjection) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_identity_events_proto protoreflect.FileDescriptor

const file_identity_events_proto_rawDesc = "" +
	"\n" +
	"\x15identity_events.proto\x12\n" +
	"identitypd\"\\\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12#\n" +
	"\rfull_snapshot\x18\x02 \x01(\bR\ffullSnapshot\"\xa8\x01\n" +
	"\rIdentityEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.identitypd.EventKindR\x04kind\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12.\n" +
	"\x04user\x18\x04 \x01(\v2\x1a.identitypd.UserProjectionR\x04user\"\xd4\x01\n" +
	"\x0eUserProjection\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12&\n" +
	"\x0fssh_public_keys\x18\x03 \x03(\tR\rsshPublicKeys\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x14\n" +
	"\x05teams\x18\x05 \x03(\tR\x05teams\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x18\n" +
	"\aversion\x18\a \x01(\x04R\aversion*d\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSNAPSHOT\x10\x01\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\x15\n" +
	"\x11SNAPSHOT_COMPLETE\x10\x042^\n" +
	"\x14IdentityEventService\x12F\n" +
	"\tSubscribe\x12\x1c.identitypd.SubscribeRequest\x1a\x19.identitypd.IdentityEvent0\x01B+Z)github.com/kthcloud/podsh/api/proto;apiv1b\x06proto3"

var (
	file_identity_events_proto_rawDescOnce sync.Once
	file_identity_events_proto_rawDescData []byte
)

func file_identity_events_proto_rawDescGZIP() []byte {
	file_identity_events_proto_rawDescOnce.Do(func() {
		file_identity_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_events_proto_rawDesc), len(file_identity_events_proto_rawDesc)))
	})
	return file_identity_events_proto_rawDescData
}

var file_identity_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_identity_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_identity_events_proto_goTypes = []any{
	(EventKind)(0),           // 0: identitypd.EventKind
	(*SubscribeRequest)(nil), // 1: identitypd.SubscribeRequest
	(*IdentityEvent)(nil),    // 2: identitypd.IdentityEvent
	(*UserProjection)(nil),   // 3: identitypd.UserProjection
}
var file_identity_events_proto_depIdxs = []int32{
	0, // 0: identitypd.IdentityEvent.kind:type_name -> identitypd.EventKind
	3, // 1: identitypd.IdentityEvent.user:type_name -> identitypd.UserProjection
	1, // 2: identitypd.IdentityEventService.Subscribe:input_type -> identitypd.SubscribeRequest
	2, // 3: identitypd.IdentityEventService.Subscribe:output_type -> identitypd.IdentityEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_events_proto_init() }
func file_identity_events_proto_init() {
	if File_identity_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_events_proto_rawDesc), len(file_identity_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_events_proto_goTypes,
		DependencyIndexes: file_identity_events_proto_depIdxs,
		EnumInfos:         file_identity_events_proto_enumTypes,
		MessageInfos:      file_identity_events_proto_msgTypes,
	}.Build()
	File_identity_events_proto = out.File
	file_identity_events_proto_goTypes = nil
	file_identity_events_proto_depIdxs = nil
}
